# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('title_link', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('source_link', models.TextField(blank=True, null=True)),
                ('news_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'news_api',
            },
        ),
    ]
